# Generated by Django 4.0.5 on 2022-07-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketset',
            name='ticketid',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('ticketsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.ticketsbase')),
            ],
            bases=('web.ticketsbase',),
        ),
        migrations.CreateModel(
            name='MultiView',
            fields=[
                ('ticketsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.ticketsbase')),
            ],
            bases=('web.ticketsbase',),
        ),
        migrations.CreateModel(
            name='SingleView',
            fields=[
                ('ticketsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.ticketsbase')),
            ],
            bases=('web.ticketsbase',),
        ),
    ]
