# Generated by Django 4.0.5 on 2022-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_ticketsbase_remove_ticketset_ticketid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketset',
            name='tickets',
            field=models.ManyToManyField(to='web.ticket'),
        ),
    ]
